#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
#  duckdb-next-build:
#    name: Build extension binaries
#    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
#    with:
#      duckdb_version: main
#      ci_tools_version: main
#      extension_name: quack

  duckdb-stable-build:
    name: Build extension binaries
    uses: samansmink/extension-ci-tools/.github/workflows/_extension_distribution.yml@minor-ci-tweaks
    with:
      duckdb_version: v1.1.3
      ci_tools_version: minor-ci-tweaks
      override_ci_tools_repository: samansmink/extension-ci-tools
      extension_name: rusty_quack
      extra_toolchains: rust;python3
      matrix_parse_script: "./extension-ci-tools/scripts/modify_distribution_matrix.py"
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: ./.github/workflows/_extension_deploy.yml
    secrets: inherit
    with:
      duckdb_version: v1.1.3
      extension_name: rusty_quack
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      matrix_parse_script: "./extension-ci-tools/scripts/modify_distribution_matrix.py"
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
